### ISSUE TITLE
How do I configure and use this package?

### ISSUE THREAD

**Issue by BirdyOz** [apas/pastery#1] opened 2015-12-09 23:36 UTC
Thanks up front for sharing.  You have introduced me to pastery, which looks like a really great pastebin alternative.

I have installed the package and tested, but nothing happens.  I imagine that it needs to be configured with my pastery API key, but can't see where to do this.  The console suggests the command is getting triggered, but I receive no status or error message and there is no pastery URL in my copy buffer.

![markdown_sample_mdown_and_new_issue_ _apas_pastery_and_inbox__113_messages__12_unread__and_login_page_mockup_pdf](https://cloud.githubusercontent.com/assets/16091439/11702316/ce4ff488-9f29-11e5-81be-b38982e9695a.png)

Thanks in advance, Greg

**Comment by skorokithakis** [comment] 2015-12-10 00:45
Pastery doesn't require the API key yet (although we probably soon will). I haven't been able to get it to run on my Linux installation either. I know that it works on OS X, maybe there are path issues?

@BirdyOz, what's your OS?

**Comment by apas** [comment] 2015-12-10 00:48
Hi Greg. First off, thanks for the kind words. Now, regarding the API key, for now it's completely optional so you don't have to worry about it.

This is how Pastery works:

![gif](http://i.imgur.com/sTJnRUf.gif)

_(By the way, you don't have to copy before triggering Pastery.)_

So long you're connected to the Internet, it should it work. Since this is really alpha, I'm not logging anything, etc. I think, though, it fails in the `curl` POST request (d'uh!) There is a bug with pastery's server that doesn't accept some requests with old SSL certificates. That's why I'm using `curl` (until @skorokithakis fixes the issue) and not a pure Python way to POST -- because on my machine the Python `urllib` failed constantly.

(@skorokithakis jumped in while I was writing this, so, I'm asking here: re: Linux installation, can you try with the ST logger on to see if the command is indeed triggered? If yes, I guess the issue is with certs, if not, it's a ST key binding one.)

**Comment by skorokithakis** [comment] 2015-12-10 00:55
I beg your pardon, but there are no SSL issues on the server:

https://www.ssllabs.com/ssltest/analyze.html?d=pastery.net

The issues are with old clients that don't support the newest cipher suites.

It looks like this bug is because Linux uses Python 3. I will have the fix ready in a few minutes.

**Comment by skorokithakis** [comment] 2015-12-10 00:58
This should work fine now, can you verify, @BirdyOz?

**Comment by apas** [comment] 2015-12-10 00:59
Good catch @skorokithakis (yes, apologies, that's what I _meant_ it's a client issue as I elaborated above -- early AMs here.) -- I've merged and tagged a new release with both of your commits. @BirdyOz let us know. Package Control should refresh every ~ half an hour or so. Restart ST and it should download latest version. If not, uninstall and install it again.

**Comment by apas** [comment] 2015-12-10 13:57
I just added support for the API key and native Python POST which fallbacks to curl, Sublime Text menus, and settings.

@BirdyOz, let Package Control refresh with latest version tag (1.1.1,) reinstall or make sure Pastery is updated, follow the new readme file to get your API key and let me know if it works/there any other problems. Cheers.

**Closed as completed** 2015-12-11 19:52 UTC
Labels: help wanted
