### ISSUE TITLE
Add support for the API key.

### ISSUE THREAD

**Issue by skorokithakis** [apas/pastery#4] opened 2015-12-10 00:59 UTC
Depending on how much abuse the service gets, we might have to make the API key mandatory. It would be good if the plugin could support it out of the box and advise users to add it, so they would not be surprised later on.

I looked into adding this and making a PR, but I don't use Sublime and I'm afraid I don't know how to set options...

**Comment by apas** [comment] 2015-12-10 01:01
Will do. Leaving this open until done.

**Comment by skorokithakis** [comment] 2015-12-10 01:13
Thank you! I've also made a few changes on the API that may make it easier for you:

https://www.pastery.net/api/

It would be much better if the plugin could use stock urllib so there's no dependency on curl. You can lift code off my Vim plugin, if you want:

https://github.com/skorokithakis/pastery.vim/

Although you'll probably still be having cert issues if the Python version on your computer uses old ciphers.

**Comment by apas** [comment] 2015-12-10 13:55
Added support for API key. https://github.com/apas/pastery/releases/tag/v1.1.0

Let Package Control refresh with latest tag, reinstall or make sure it's updated, and let me know.

**Comment by stelabouras** [comment] 2015-12-10 14:06
Confirmed under OSX/ST2.0.2 It works :+1:  Thanks @apas!

**Comment by stelabouras** [comment] 2015-12-10 14:11
Uhm, I don't know if it's me but in ST3 b3083 I can't edit the Pastery settings in order to enter my API key.

Actually I don't see a 'Settings - User' option and I think that's the reason why (The 'Settings - Default' is read-only).

![](https://dl.dropboxusercontent.com/u/20485/pastery-sublime.png)

**Comment by apas** [comment] 2015-12-10 14:26
It's not you - ST3 locks the settings. Will patch with a User settings file, not a Default.

**Comment by apas** [comment] 2015-12-10 15:59
@stelabouras check https://github.com/apas/pastery/releases/tag/v1.1.1 Should work. Tested locally in ST3 + 2.

**Comment by stelabouras** [comment] 2015-12-10 17:12
OK, I can confirm that it now works both in ST 2 + 3 now but I had to manually c/p the text of 'Settings - Default' to 'Settings - User' as it was totally empty. Can it be so that the 'Settings - User' contains the same data as the 'Settings - Default'? Man, ST makes it really difficult to manage the Package preferences.

**Comment by apas** [comment] 2015-12-10 17:21
No, you can't. The User settings file essentially doesn't exist and you create/save it on-demand. ST3 changes how packages work, hence the compatibility issue -- go figure… I'm closing this now.

**Closed as completed** 2015-12-10 17:21 UTC
Labels: enhancement
